#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false

    filemanager = "nerdtree"
    enable_tabline_filetype_icon = 0
    enable_statusline_display_mode = 1
    enable_ale = 1
    enable_neomake = 0
    windows_leader = "?"
    windows_smartclose = ""
    relativenumber = 0
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    lint_on_the_fly = 1

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "shell"
enable = false
#default_position = "top"
#default_height = 30

[[layers]]
name = "ui"
enable = false

[[layers]]
name = "VersionControl"

[[layers]]
name = "colorscheme"

[[layers]]
name = "ctrlp"

[[layers]]
name = "git"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#vim"

[[custom_plugins]]
name = "christoomey/vim-tmux-navigator"

[[custom_plugins]]
name = "Yggdroot/indentLine"

